services:
  next:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - WATCHPACK_POLLING=true
      - NEXT_CACHE_DIR=/app/.next/cache